const fs = require('fs');
const path = require('path');

// We have temp-cropped.png generated by PowerShell
if (fs.existsSync('temp-cropped.png')) {
  const buf = fs.readFileSync('temp-cropped.png');
  const targets = [
    'public/logo.png',
    'public/icon.png',
    'public/icon-192.png',
    'public/icon-512.png',
    'src/app/icon.png',
    'src/app/apple-icon.png'
  ];
  for (const t of targets) {
    fs.writeFileSync(path.resolve(t), buf);
    console.log('Successfully written:', t, buf.length, 'bytes');
  }
  fs.unlinkSync('temp-cropped.png');
}
