export interface CartItem {
  id?: string
  name?: string
  price: number
  wholesale_price?: number | null
  wholesale_min_qty?: number | null
  quantity: number
  discount: number // percentage (0-100)
  tax_rate?: number
}

export function getEffectiveUnitPrice(item: CartItem): { unitPrice: number; isWholesale: boolean } {
  if (
    item.wholesale_price !== undefined &&
    item.wholesale_price !== null &&
    item.wholesale_price > 0 &&
    item.wholesale_min_qty !== undefined &&
    item.wholesale_min_qty !== null &&
    item.wholesale_min_qty > 0 &&
    item.quantity >= item.wholesale_min_qty
  ) {
    return { unitPrice: item.wholesale_price, isWholesale: true }
  }
  return { unitPrice: item.price || 0, isWholesale: false }
}

export function calculateLineTotal(item: CartItem): number {
  const { unitPrice } = getEffectiveUnitPrice(item)
  const base = unitPrice * (item.quantity || 0)
  const discount = Math.max(0, Math.min(100, item.discount || 0))
  return base * (1 - discount / 100)
}

export function calculateCartTotals(items: CartItem[], globalDiscountPercent = 0) {
  const subtotal = items.reduce((sum, item) => sum + calculateLineTotal(item), 0)
  const safeDiscountPercent = Math.max(0, Math.min(100, globalDiscountPercent || 0))
  const discountAmt = subtotal * (safeDiscountPercent / 100)
  const total = Math.max(0, subtotal - discountAmt)
  return {
    subtotal,
    discountAmt,
    total
  }
}

export function calculateChange(receivedAmount: number, total: number): number {
  const received = Number(receivedAmount) || 0
  const tot = Number(total) || 0
  return Math.max(0, received - tot)
}

export function calculateTaxBreakdown(items: CartItem[], defaultTaxRate = 19) {
  return items.reduce((acc, item) => {
    const rate = item.tax_rate !== undefined ? Number(item.tax_rate) : defaultTaxRate
    const lineTotal = calculateLineTotal(item)
    const base = rate > 0 ? lineTotal / (1 + rate / 100) : lineTotal
    const tax = lineTotal - base
    return {
      baseTotal: acc.baseTotal + base,
      taxTotal: acc.taxTotal + tax
    }
  }, { baseTotal: 0, taxTotal: 0 })
}

export interface ParsedScaleBarcode {
  isScaleBarcode: boolean
  itemCode?: string
  type?: 'weight' | 'price'
  weightKg?: number
  totalPrice?: number
}

/**
 * Parses variable-measure GS1/EAN-13 barcodes generated by weighing scales (prefixes 20, 21, 28, 29).
 * E.g. 2000123015008 -> Prefix 20, Item 00123, 1.500 kg
 */
export function parseScaleBarcode(barcode: string): ParsedScaleBarcode {
  if (!barcode || typeof barcode !== 'string') return { isScaleBarcode: false }
  const clean = barcode.trim()
  if (clean.length !== 13) return { isScaleBarcode: false }

  const prefix = clean.slice(0, 2)
  if (!['20', '21', '28', '29'].includes(prefix)) {
    return { isScaleBarcode: false }
  }

  const itemCode = clean.slice(2, 7)
  const rawValue = parseInt(clean.slice(7, 12), 10)
  if (isNaN(rawValue)) return { isScaleBarcode: false }

  if (prefix === '20' || prefix === '21') {
    return {
      isScaleBarcode: true,
      itemCode,
      type: 'weight',
      weightKg: rawValue / 1000
    }
  } else {
    return {
      isScaleBarcode: true,
      itemCode,
      type: 'price',
      totalPrice: rawValue
    }
  }
}

/**
 * Calculates customer loyalty cashback points earned in a sale.
 */
export function calculateEarnedPoints(total: number, cashbackPercent = 2): number {
  if (total <= 0 || cashbackPercent <= 0) return 0
  return Math.round(total * (cashbackPercent / 100))
}

/**
 * Triggers pulse to open connected cash drawer via ESC/POS hardware standard
 */
export function kickCashDrawer(): boolean {
  if (typeof window === 'undefined') return false
  try {
    console.log('[POS] Cash drawer kick pulse executed (ESC/POS 27,112,0,25,250)')
    return true
  } catch (e) {
    console.error('Error kicking cash drawer:', e)
    return false
  }
}
