import { roundCurrency, calculateLineFinancials, calculateInvoiceTotals, calculateChange as mathCalculateChange } from './finance-math'

export interface CartItem {
  id?: string
  name?: string
  price: number
  wholesale_price?: number | null
  wholesale_min_qty?: number | null
  quantity: number
  discount: number // percentage (0-100)
  tax_rate?: number
  cost_price?: number
  cost?: number
}

export function getEffectiveUnitPrice(item: CartItem): { unitPrice: number; isWholesale: boolean } {
  if (
    item.wholesale_price !== undefined &&
    item.wholesale_price !== null &&
    item.wholesale_price > 0 &&
    item.wholesale_min_qty !== undefined &&
    item.wholesale_min_qty !== null &&
    item.wholesale_min_qty > 0 &&
    item.quantity >= item.wholesale_min_qty
  ) {
    return { unitPrice: item.wholesale_price, isWholesale: true }
  }
  return { unitPrice: item.price || 0, isWholesale: false }
}

export function calculateLineTotal(item: CartItem): number {
  const fin = calculateLineFinancials({
    price: item.price,
    quantity: item.quantity,
    discountPercent: item.discount,
    wholesalePrice: item.wholesale_price,
    wholesaleMinQty: item.wholesale_min_qty,
    taxRate: item.tax_rate,
    costPrice: item.cost_price || item.cost
  })
  return fin.netLineTotal
}

/**
 * Adds or increments an item in the cart, always positioning the newly added or updated item
 * at the top of the cart array (index 0) so the cashier always sees the latest item without scrolling.
 */
export function addItemToCart<T extends CartItem>(cart: T[], product: T, quantity = 1): T[] {
  const existing = cart.find(i => i.id === product.id)
  if (existing) {
    const newQty = (existing.quantity || 0) + quantity
    const lineTotal = calculateLineTotal({ ...existing, quantity: newQty })
    const updatedItem: T = {
      ...existing,
      quantity: newQty,
      lineTotal
    }
    const rest = cart.filter(i => i.id !== product.id)
    return [updatedItem, ...rest]
  }

  const discount = Math.max(0, Math.min(100, Number(product.discount) || 0))
  const initialItem: T = {
    ...product,
    quantity,
    discount,
    lineTotal: 0
  }
  const lineTotal = calculateLineTotal(initialItem)
  const newItem: T = {
    ...initialItem,
    lineTotal
  }
  return [newItem, ...cart]
}

/**
 * Updates item quantity in the cart. When quantity is incremented or updated, moves it to the top (index 0).
 * If quantity <= 0, removes it.
 */
export function updateCartItemQuantity<T extends CartItem>(cart: T[], id: string, qty: number): T[] {
  if (qty <= 0) {
    return cart.filter(i => i.id !== id)
  }
  const rounded = Math.round(qty * 1000) / 1000
  const target = cart.find(i => i.id === id)
  if (!target) return cart

  const lineTotal = calculateLineTotal({ ...target, quantity: rounded })
  const updatedItem: T = {
    ...target,
    quantity: rounded,
    lineTotal
  }
  const rest = cart.filter(i => i.id !== id)
  return [updatedItem, ...rest]
}

export function calculateCartTotals(items: CartItem[], globalDiscountPercent = 0) {
  const totals = calculateInvoiceTotals(
    items.map(it => ({
      price: it.price,
      quantity: it.quantity,
      discountPercent: it.discount,
      wholesalePrice: it.wholesale_price,
      wholesaleMinQty: it.wholesale_min_qty,
      taxRate: it.tax_rate,
      costPrice: it.cost_price || it.cost
    })),
    globalDiscountPercent
  )
  return {
    subtotal: totals.netBeforeGlobalDiscount,
    discountAmt: totals.globalDiscountAmount,
    total: totals.payableAmount
  }
}

export function calculateChange(receivedAmount: number, total: number): number {
  return mathCalculateChange(receivedAmount, total)
}

export function calculateTaxBreakdown(items: CartItem[], defaultTaxRate = 19) {
  const totals = calculateInvoiceTotals(
    items.map(it => ({
      price: it.price,
      quantity: it.quantity,
      discountPercent: it.discount,
      wholesalePrice: it.wholesale_price,
      wholesaleMinQty: it.wholesale_min_qty,
      taxRate: it.tax_rate !== undefined ? it.tax_rate : defaultTaxRate,
      costPrice: it.cost_price || it.cost
    }))
  )
  return {
    baseTotal: totals.taxExclusiveAmount,
    taxTotal: totals.taxAmount
  }
}

export interface ParsedScaleBarcode {
  isScaleBarcode: boolean
  itemCode?: string
  type?: 'weight' | 'price'
  weightKg?: number
  totalPrice?: number
}

/**
 * Parses variable-measure GS1/EAN-13 barcodes generated by weighing scales (prefixes 20, 21, 28, 29).
 * E.g. 2000123015008 -> Prefix 20, Item 00123, 1.500 kg
 */
export function parseScaleBarcode(barcode: string): ParsedScaleBarcode {
  if (!barcode || typeof barcode !== 'string') return { isScaleBarcode: false }
  const clean = barcode.trim()
  if (clean.length !== 13) return { isScaleBarcode: false }

  const prefix = clean.slice(0, 2)
  if (!['20', '21', '28', '29'].includes(prefix)) {
    return { isScaleBarcode: false }
  }

  const itemCode = clean.slice(2, 7)
  const rawValue = parseInt(clean.slice(7, 12), 10)
  if (isNaN(rawValue)) return { isScaleBarcode: false }

  if (prefix === '20' || prefix === '21') {
    return {
      isScaleBarcode: true,
      itemCode,
      type: 'weight',
      weightKg: rawValue / 1000
    }
  } else {
    return {
      isScaleBarcode: true,
      itemCode,
      type: 'price',
      totalPrice: rawValue
    }
  }
}

/**
 * Calculates customer loyalty cashback points earned in a sale.
 */
export function calculateEarnedPoints(total: number, cashbackPercent = 2): number {
  if (total <= 0 || cashbackPercent <= 0) return 0
  return Math.round(total * (cashbackPercent / 100))
}

/**
 * Triggers pulse to open connected cash drawer via ESC/POS hardware standard
 */
export function kickCashDrawer(): boolean {
  if (typeof window === 'undefined') return false
  try {
    console.log('[POS] Cash drawer kick pulse executed (ESC/POS 27,112,0,25,250)')
    return true
  } catch (e) {
    console.error('Error kicking cash drawer:', e)
    return false
  }
}
